import{a as y,i as c,S as d}from"./assets/vendor-itfKyfJC.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(r){if(r.ep)return;r.ep=!0;const t=a(r);fetch(r.href,t)}})();const h="https://pixabay.com/api/",L="48823979-822a726f00604f1f8a353c21f";async function S(s){const o={key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,mode:"cors",per_page:40,page:1},a=document.querySelector(".loader");a.style.display="block";const n=await y.get(h,{params:o});try{const r=n.data.hits;return r.length===0&&c.error({position:"topRight",color:"red",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),r}catch(r){return c.error({message:"Sorry. Please try again!"}),console.error("Fetch error:",r),[]}finally{a.style.display="none"}}const p=document.querySelector(".gallery");function b(s){p.innerHTML="";const o=s.map(({webformatURL:a,largeImageURL:n,tags:r,likes:t,views:i,comments:m,downloads:f})=>`<a href="${n}" class="gallery-item">
            <img src="${a}" alt="${r}" class="gallery-image" />
            <div class="info">
                <p><strong>Likes:</strong> ${t}</p>
                <p><strong>Views:</strong> ${i}</p>
                <p><strong>Comments:</strong> ${m}</p>
                <p><strong>Downloads:</strong> ${f}</p>
            </div> 
        </a>`).join("");p.innerHTML=o,new d(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const u=document.querySelector("#form"),g=document.querySelector(".loader"),l=e.target.elements.text.value.trim();u.addEventListener("submit",async s=>{if(s.preventDefault(),!l||/^\d+$/.test(l)){c.error({message:"Please enter a search query!",position:"topRight",color:"yellow"});return}g.style.display="block";try{const o=await S(l);b(o)}catch{c.error({message:"There was an error fetching the images."})}finally{g.style.display="none",u.reset()}});
//# sourceMappingURL=index.js.map
