import{a as S,i,S as q}from"./assets/vendor-itfKyfJC.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",H="48823979-822a726f00604f1f8a353c21f";async function u(r,o){const s={key:H,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,mode:"cors",per_page:40,page:o},n=document.querySelector(".loader");n.style.display="block";try{const e=await S.get(v,{params:s}),t=e.data.hits,a=e.data.totalHits;return t.length===0&&i.error({position:"topRight",color:"red",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),{images:t,totalHits:a}}catch(e){return i.error({message:"Sorry. Please try again!"}),console.error("Fetch error:",e),{images:[],totalHits:0}}finally{n.style.display="none"}}const P=document.querySelector(".gallery");function m(r){const o=r.map(({webformatURL:n,largeImageURL:e,tags:t,likes:a,views:L,comments:w,downloads:b})=>`<a href="${e}" class="gallery-item">
            <img src="${n}" alt="${t}" class="gallery-image" />
            <div class="info">
                <p><strong>Likes:</strong> ${a}</p>
                <p><strong>Views:</strong> ${L}</p>
                <p><strong>Comments:</strong> ${w}</p>
                <p><strong>Downloads:</strong> ${b}</p>
            </div> 
        </a>`).join("");P.insertAdjacentHTML("beforeend",o),new q(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const y=document.querySelector("#form"),c=document.querySelector(".loader"),g=document.querySelector(".load-more"),p=document.querySelector(".gallery");let l="",d=1,f=0;y.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements.text.value.trim(),d=1,p.innerHTML="",h(),!l){i.error({message:"Please enter a search query!",position:"topRight",color:"yellow"});return}c.style.display="block";try{const{images:o,totalHits:s}=await u(l,d);f=s,m(o)}catch{i.error({message:"There was an error fetching the images.",position:"topRight",color:"red"})}finally{c.style.display="none",y.reset()}$()});function $(){g.classList.remove("hidden")}function h(){g.classList.add("hidden")}function E(){i.info({position:"topRight",message:"Sorry, you've reached the end of search results.",color:"red"})}function M(){const r=document.querySelector(".gallery-item:last-child");if(r){const s=r.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}g.addEventListener("click",async()=>{d+=1,c.style.display="block";try{const{images:r}=await u(l,d);m(r),M(),p.children.length>=f&&(h(),E())}catch(r){console.error("Fetch error:",r)}finally{c.style.display="none"}});
//# sourceMappingURL=index.js.map
