import{a as S,i as l,S as q}from"./assets/vendor-itfKyfJC.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",H="48823979-822a726f00604f1f8a353c21f";async function g(r,o){const s={key:H,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,mode:"cors",per_page:40,page:o},n=document.querySelector(".loader");n.style.display="block";try{const e=await S.get(v,{params:s}),t=e.data.hits,a=e.data.totalHits;return{images:t,totalHits:a}}catch(e){return l.error({message:"Sorry. Please try again!"}),console.error("Fetch error:",e),{images:[],totalHits:0}}finally{n.style.display="none"}}const $=document.querySelector(".gallery");function m(r){const o=r.map(({webformatURL:n,largeImageURL:e,tags:t,likes:a,views:L,comments:w,downloads:b})=>`<a href="${e}" class="gallery-item">
            <img src="${n}" alt="${t}" class="gallery-image" />
            <div class="info">
                <p><strong>Likes:</strong> ${a}</p>
                <p><strong>Views:</strong> ${L}</p>
                <p><strong>Comments:</strong> ${w}</p>
                <p><strong>Downloads:</strong> ${b}</p>
            </div> 
        </a>`).join("");$.insertAdjacentHTML("beforeend",o),new q(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const u=document.querySelector("#form"),c=document.querySelector(".loader"),y=document.querySelector(".load-more"),f=document.querySelector(".gallery");let i="",d=1,p=0;u.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements.text.value.trim(),d=1,f.innerHTML="",!i||/^\d+$/.test(i.trim())){l.error({message:"Please enter a search query!",position:"topRight",color:"yellow"});return}h(),c.style.display="block";try{const{images:o,totalHits:s}=await g(i,d);p=s,m(o)}catch{l.error({message:"There was an error fetching the images.",position:"topRight",color:"red"})}finally{c.style.display="none",u.reset()}M()});function M(){y.classList.remove("hidden")}function h(){y.classList.add("hidden")}function P(){l.info({position:"topRight",message:"Sorry, you've reached the end of search results.",color:"red"})}function x(){const r=document.querySelector(".gallery-item:last-child");if(r){const s=r.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}y.addEventListener("click",async()=>{d+=1,c.style.display="block";try{const{images:r}=await g(i,d);m(r),x(),f.children.length>=p&&(h(),P())}catch(r){console.error("Fetch error:",r)}finally{c.style.display="none"}});
//# sourceMappingURL=index.js.map
